name: Blogs-sync

on:
  schedule:
    - cron: "0 0 * * 0" # Run on Mondays
  workflow_dispatch:
  push:
    branches: ["v1"]

permissions:
  contents: write

jobs:
  save-articles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run DevtoGitHub
        uses: Anmol-Baranwal/DevtoGitHub@v1
        with:
          devApiKey: ${{ secrets.DEV_TOKEN }}
          saveArticles: true
          outputDir: "articles"
          saveArticlesReadme: true # this will create a table of content for easy navigation
